# Generated by Django 4.0.3 on 2022-04-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hipervinculo', models.CharField(max_length=300, verbose_name='Hipervinculo:')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título:')),
            ],
        ),
    ]
