# Generated by Django 4.0.3 on 2022-04-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condicion_iva', '0001_initial'),
        ('cliente', '0002_remove_cliente_dni_cliente_numdocumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicioniva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condicion_iva.condicion_iva'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuilcuit',
            field=models.CharField(max_length=20, verbose_name='Número:'),
        ),
    ]
