# Generated by Django 4.0.3 on 2022-04-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0002_alter_emprendedor_dni'),
        ('empresa', '0001_initial'),
        ('proy_aprendizaje', '0002_remove_proy_aprendizaje_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proy_aprendizaje',
            name='departamento',
        ),
        migrations.AddField(
            model_name='proy_aprendizaje',
            name='emprendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emprendedor.emprendedor'),
        ),
        migrations.AddField(
            model_name='proy_aprendizaje',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
