# Generated by Django 4.0.3 on 2022-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_prueba_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
    ]
