# Generated by Django 4.0.3 on 2022-04-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_prueba_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Home',
        ),
    ]
