# Generated by Django 4.0.3 on 2022-04-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_prueba_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Prueba',
        ),
    ]
