# Generated by Django 4.0.3 on 2022-04-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condicion_iva', '0001_initial'),
        ('tipo_documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numdocumento', models.CharField(default=' ', max_length=20)),
                ('numeroiva', models.CharField(default=' ', max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('condicioniva', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condicion_iva.condicion_iva')),
                ('tipodocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_documento.tipo_documento')),
            ],
        ),
    ]
