# Generated by Django 4.0.3 on 2022-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
