# Generated by Django 4.0.3 on 2022-04-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha:')),
                ('detalle', models.CharField(max_length=200, verbose_name='Referencia:')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Débito/Crédito:')),
                ('observaciones', models.CharField(default=' ', max_length=20, verbose_name='Observaciones:')),
                ('idcuenta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuenta.cuenta')),
            ],
        ),
    ]
