# Generated by Django 4.0.3 on 2022-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_cuenta',
            name='idasiento',
            field=models.IntegerField(default=0, verbose_name='Asiento:'),
        ),
    ]
